flowchart TD
  subgraph MAX 1
  10
  15
  7
  9
  end
  subgraph MIN 2
  6
  5
  2
  8
  0
  4
  3
  1
  end
  当前盘面 --> 10
  10 --> 6
  10 --> 5
  当前盘面 --> 15
  15 --> 2
  15 --> 8
  当前盘面 --> 7
  7 --> 0
  7 --> 4
  当前盘面 --> 9
  9 --> 3
  9 --> 1