graph LR
    D((3)):::bigCircle
    A((x₁)):::noShape --> |-2| D
    B((x₂)):::noShape --> |-2| D
    D --> E(( )):::noShape
    
    classDef bigCircle stroke:#333,stroke-width:2,r:50;
    classDef noShape fill:transparent,stroke:transparent;