graph LR
    D(( )):::bigCircle
    A((x₁)):::noShape --> |w₁| D
    B((x₂)):::noShape --> |w₂| D
    C((x₃)):::noShape --> |w₃| D
    D --> E((output)):::noShape
    
    classDef bigCircle stroke:#333,stroke-width:2,r:50;
    classDef noShape fill:transparent,stroke:transparent;